# Site settings
title: ZUP – Zeladoria Urbana Participativa
email: your-email@domain.com
description: >
  Torne sua cidade mais eficiente através da comunicação direta
  entre orgãos públicos e munícipes.

# baseurl: "/docs/" # the subpath of your site, e.g. /blog/
url: https://github.com/institutotim/zup-docs # the base hostname & protocol for your site
git_address: https://github.com/institutotim/zup-docs
git_edit_address: https://github.com/institutotim/zup-docs/blob/jekyll

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Sao_Paulo
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
